
-- 1) Categorías
INSERT INTO CATEGORIA (NOMBRE) VALUES ('Novela');
INSERT INTO CATEGORIA (NOMBRE) VALUES ('Tecnología');
INSERT INTO CATEGORIA (NOMBRE) VALUES ('Historia');
INSERT INTO CATEGORIA (NOMBRE) VALUES ('Filosofía');
INSERT INTO CATEGORIA (NOMBRE) VALUES ('Ciencia');

-- 2) Libros
INSERT INTO LIBRO (TITULO, UNIDADES, CATEGORIA_ID)
SELECT 'Cien años de soledad', 5, c.ID FROM CATEGORIA c WHERE c.NOMBRE='Novela';

INSERT INTO LIBRO (TITULO, UNIDADES, CATEGORIA_ID)
SELECT 'Refactoring', 3, c.ID FROM CATEGORIA c WHERE c.NOMBRE='Tecnología';

INSERT INTO LIBRO (TITULO, UNIDADES, CATEGORIA_ID)
SELECT 'Sapiens', 4, c.ID FROM CATEGORIA c WHERE c.NOMBRE='Historia';

INSERT INTO LIBRO (TITULO, UNIDADES, CATEGORIA_ID)
SELECT 'El mundo de Sofía', 2, c.ID FROM CATEGORIA c WHERE c.NOMBRE='Filosofía';

INSERT INTO LIBRO (TITULO, UNIDADES, CATEGORIA_ID)
SELECT 'Breves respuestas a grandes preguntas', 3, c.ID FROM CATEGORIA c WHERE c.NOMBRE='Ciencia';

-- 3) Autores
INSERT INTO AUTOR (NOMBRE, PAIS) VALUES ('Gabriel García Márquez','Colombia');
INSERT INTO AUTOR (NOMBRE, PAIS) VALUES ('Martin Fowler','Reino Unido');
INSERT INTO AUTOR (NOMBRE, PAIS) VALUES ('Yuval Noah Harari','Israel');
INSERT INTO AUTOR (NOMBRE, PAIS) VALUES ('Jostein Gaarder','Noruega');
INSERT INTO AUTOR (NOMBRE, PAIS) VALUES ('Stephen Hawking','Reino Unido');

-- 4) Relaciones libro ↔ autor
INSERT INTO LIBRO_AUTOR (LIBRO_ID, AUTOR_ID)
SELECT l.ID, a.ID FROM LIBRO l
JOIN AUTOR a ON a.NOMBRE='Gabriel García Márquez' WHERE l.TITULO='Cien años de soledad';

INSERT INTO LIBRO_AUTOR (LIBRO_ID, AUTOR_ID)
SELECT l.ID, a.ID FROM LIBRO l
JOIN AUTOR a ON a.NOMBRE='Martin Fowler' WHERE l.TITULO='Refactoring';

INSERT INTO LIBRO_AUTOR (LIBRO_ID, AUTOR_ID)
SELECT l.ID, a.ID FROM LIBRO l
JOIN AUTOR a ON a.NOMBRE='Yuval Noah Harari' WHERE l.TITULO='Sapiens';

INSERT INTO LIBRO_AUTOR (LIBRO_ID, AUTOR_ID)
SELECT l.ID, a.ID FROM LIBRO l
JOIN AUTOR a ON a.NOMBRE='Jostein Gaarder' WHERE l.TITULO='El mundo de Sofía';

INSERT INTO LIBRO_AUTOR (LIBRO_ID, AUTOR_ID)
SELECT l.ID, a.ID FROM LIBRO l
JOIN AUTOR a ON a.NOMBRE='Stephen Hawking' WHERE l.TITULO='Breves respuestas a grandes preguntas';

-- 5) Ejemplares
INSERT INTO EJEMPLAR (LIBRO_ID, PRESTADO)
SELECT ID, FALSE FROM LIBRO;

-- 6) Préstamos (Usuarios 1 y 2, usando los primeros ejemplares)
-- ACTIVO
INSERT INTO PRESTAMO (USUARIO_ID, EJEMPLAR_ID, FECHA_PRESTAMO, FECHA_DEVOLUCION, FECHA_VENCE, MULTA, ESTADO)
VALUES (1, 1, '2025-08-10', NULL, '2025-08-24', 0, 'ACTIVO');

-- CON_MORA
INSERT INTO PRESTAMO (USUARIO_ID, EJEMPLAR_ID, FECHA_PRESTAMO, FECHA_DEVOLUCION, FECHA_VENCE, MULTA, ESTADO)
VALUES (1, 2, '2025-07-20', '2025-08-10', '2025-08-03', 2100, 'CON_MORA');

-- DEVUELTO
INSERT INTO PRESTAMO (USUARIO_ID, EJEMPLAR_ID, FECHA_PRESTAMO, FECHA_DEVOLUCION, FECHA_VENCE, MULTA, ESTADO)
VALUES (2, 3, '2025-07-01', '2025-07-10', '2025-07-15', 0, 'DEVUELTO');

-- CON_MORA
INSERT INTO PRESTAMO (USUARIO_ID, EJEMPLAR_ID, FECHA_PRESTAMO, FECHA_DEVOLUCION, FECHA_VENCE, MULTA, ESTADO)
VALUES (2, 4, '2025-07-05', '2025-07-25', '2025-07-19', 1800, 'CON_MORA');

-- ACTIVO
INSERT INTO PRESTAMO (USUARIO_ID, EJEMPLAR_ID, FECHA_PRESTAMO, FECHA_DEVOLUCION, FECHA_VENCE, MULTA, ESTADO)
VALUES (1, 5, '2025-08-15', NULL, '2025-08-29', 0, 'ACTIVO');

